nome = str(input('Digite seu nome completo: ')).strip()
dividido = nome.split()
print('_'*100)
print('<<Analisando seu nome...>> ')
print('Seu nome em maiúsculas é',nome.upper())
print('Seu nome em minúsculas é',nome.lower())
print('Seu nome tem ao todo',len(nome)-nome.count(' '),'letras')
print('Seu primeiro nome é',dividido[0],'e ele tem',len(dividido[0]),'letras')
print('_'*100)